doodlepoll/config/routes.rb
Rails.application.routes.draw do
  resources :polls

  root 'polls#index'

end

doodlepoll/app/models/poll.rb
class Poll < ActiveRecord::Base
end

doodlepoll/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

doodlepoll/app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all
    render :index
  end

  def show
    @poll = Poll.find(params[:id])
    render :show
  end

  def new
    @poll = Poll.new
    render :new
  end

  def create
    @poll = Poll.new(params[:poll])
    @poll.save
    redirect_to action: 'show', id: @poll.id
  end


end

doodlepoll/app/helpers/application_helper.rb
module ApplicationHelper
end

doodlepoll/app/helpers/polls_helper.rb
module PollsHelper
end

doodlepoll/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doodlepoll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

doodlepoll/app/views/polls/index.erb
<h1>Polls</h1>
<% @polls.each do |poll| %>
  <%= link_to(poll.name, poll_path(poll)) %>
<% end %>

doodlepoll/app/views/polls/new.html.erb
<h1>New Poll</h1>

<form id='form_stuff'>
  <input id='name' type="text">
  <input type="submit">
</form>

<script type="text/javascript">
  $('#form_stuff').on("submit", function(){
    $.ajax({
      url: "poll",
      type: "post",
      dataType: "json"
      data: $('#name').value
    }).done({})
  })
</script>

doodlepoll/app/views/polls/show.html.erb
<h1>Show Page</h1>